LineLength:
  Max: 99

SignalException:
  EnforcedStyle: only_raise

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

TrailingCommaInArguments:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true
  EnforcedStyle: final_newline
  SupportedStyles:
  - final_newline
  - final_blank_line

Layout/TrailingWhitespace:
  Enabled: true

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - db/**/*

Documentation:
  Enabled: false
