dist: trusty
sudo: required
language: ruby
cache: bundler

rvm:
  - 2.4.3

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

env:
  global:
    - RAILS_ENV=test
    - MYSQL_PASSWORD=''

before_script:
  - bundle exec rake db:setup

after_success:
  - >
    [ "${TRAVIS_PULL_REQUEST}" != "false" ] &&
    #[ "${TRAVIS_RUBY_VERSION}" = "2.4.3" ] &&
      PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} \
        bundle exec pronto run -f github_pr -c origin/${TRAVIS_BRANCH}
