sudo: required
services:
  - docker
env:
  COMPOSE_VERSION: 1.11.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo "PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST}" >> .env
  - echo "PRONTO_GITHUB_ACCESS_TOKEN=${PRONTO_GITHUB_ACCESS_TOKEN}" >> .env
install:
  - git fetch origin master:master

before_script:
  - chmod +x run-tests-in-docker.sh
script: ./run-tests-in-docker.sh
