version: '3'

services:
  app:
    image: vilnius/tvarkauvilniums:production
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
