version: '2'

# Test configuration
# with dynamic port bindings for parallel execution
# and a custom entry point
#
# docker-compose -f docker-compose.test.yml up

services:
  app:
    build: .
    volumes:
      - .:/opt/tvarkau-vilniu
    ports:
      - "3000"
    links:
      - db
    environment:
      RAILS_ENV: test
      TVARKAU_VILNIU_DB_HOST: db
      TVARKAU_VILNIU_DB_PORT: 3306
      PULL_REQUEST_ID: ${PULL_REQUEST_ID}
      PRONTO_GITHUB_ACCESS_TOKEN: ${PRONTO_GITHUB_ACCESS_TOKEN}
    entrypoint: ./wait-for-it.sh db:3306 -t 60 -- ./docker-entrypoint-test.sh
    volumes:
      - box:/box
  db:
    image: mysql:5.7.20
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: a

volumes:
  box:
    driver: local
