version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /box/.bundle
    volumes:
      - .:/opt/tvarkau-vilniu
      - box:/box
  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
  box:
    driver: local
