version: '2'

# Test configuration
# with dynamic port bindings for parallel execution
# and a custom entry point
#
# docker-compose -f docker-compose.test.yml up

services:
  app:
    build: .
    ports:
      - "3000"
    links:
      - db
    environment:
      RAILS_ENV: test
      TVARKAU_VILNIU_RAILS_DB_HOST: db
      TVARKAU_VILNIU_RAILS_DB_PORT: 5432
      STORAGE_ENDPOINT: http://storage:9000
      STORAGE_ACCESS_KEY: development
      STORAGE_SECRET_KEY: development
      PULL_REQUEST_ID: ${PULL_REQUEST_ID}
      PRONTO_GITHUB_ACCESS_TOKEN: ${PRONTO_GITHUB_ACCESS_TOKEN}
    entrypoint: ./wait-for-it.sh db:5432 -- ./docker-entrypoint-test.sh
  db:
    image: postgres:9.5.6
    mem_limit: 300m
    ports:
      - "5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: tvarkau_vilniu_rails_test
      POSTGRES_USER: vilnius
      POSTGRES_PASSWORD: vilnius
  storage:
    image: minio/minio
    ports:
      - "9000"
    entrypoint: minio server /export
    environment:
      MINIO_ACCESS_KEY: development
      MINIO_SECRET_KEY: development
    volumes:
      - ./test/.minio/data:/export
      - ./test/.minio/config:/root/.minio
  storage-init:
    links:
      - storage
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
        while ! wget -q -s http://storage:9000/minio/login; do sleep 1; done;
        mc config host add minio http://storage:9000 development development
        mc mb minio/photos
        exit 0
      "