version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: development
      TVARKAU_VILNIU_DB_HOST: db
      TVARKAU_VILNIU_DB_PORT: 3306
    command: ./wait-for-it.sh db:3306 -t 60 -- ./docker-entrypoint.sh
    volumes:
      - .:/opt/tvarkau-vilniu
      - box:/box
  db:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
  box:
    driver: local
