version: '2'

# Default (development) configuration
# with dynamic port bindings for parallel execution
#
# docker-compose up

services:
  app:
    build: .
    volumes:
      - .:/opt/tvarkau-vilniu
    ports:
      - "3000:3000"
    links:
      - db
      - mysql
    environment:
      RAILS_ENV: development
      TVARKAU_VILNIU_RAILS_DB_HOST: db
      TVARKAU_VILNIU_RAILS_DB_PORT: 5432
      TVARKAU_VILNIU_DB_HOST: mysql
      TVARKAU_VILNIU_DB_PORT: 3306
  db:
    image: postgres:9.5.6
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    mem_limit: 300m
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: tvarkau_vilniu_rails_development
      POSTGRES_USER: vilnius
      POSTGRES_PASSWORD: vilnius
  mysql:
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tvarkau_miesta_development
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - /var/lib/mysql
      - ./db_vilnius:/docker-entrypoint-initdb.d
volumes:
  postgresql-data:
    driver: local
