defaults: &defaults
  storage_endpoint: <%= ENV['STORAGE_ENDPOINT'] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY'] %>
  storage_secret_key: <%= Secret['STORAGE_SECRET_KEY'] %>
  storage_bucket: photos

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
