default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'a' %>

development:
  <<: *default
  database: tvarkau_vilniu_development

test:
  <<: *default
  database: tvarkau_vilniu_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'tvarkau_vilniu' %>
