default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['TVARKAU_VILNIU_DB_HOST'] || localhost %>
  port: <%= ENV['TVARKAU_VILNIU_DB_PORT'] || 3306 %>
  username: <%= ENV['TVARKAU_VILNIU_DB_USER'] || vilnius %>
  password: <%= ENV['TVARKAU_VILNIU_DB_PASSWORD'] || vilnius %>

development:
  <<: *default
  database: tvarkau_miesta_development

test:
  <<: *default
  host: localhost
  database: tvarkau_miesta_test
  username: root
  password: a

production:
  <<: *default
  database: tvarkau_miesta
