default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: ENV['TVARKAU_VILNIU_DB_HOST']
  username: ENV['TVARKAU_VILNIU_DB_USER']
  password: ENV['TVARKAU_VILNIU_DB_PASSWORD']

development:
  <<: *default
  database: tvarkau_miesta

test:
  <<: *default
  host: localhost
  database: tvarkau_miesta_test
  username: root
  password: a

production:
  <<: *default
  database: tvarkau_miesta
